### ISSUE TITLE
Club Manager Removal

### ISSUE THREAD

**Issue by hiimchrislim** [2-of-clubs/2ofclubs-server#31]
Should club managers also have the ability to remove themselves/leave?

**Comment by MichaelLiut** [comment]
Yes. If a manager is also the owner, it should go to the next in-line (i.e. the next person who became a manager). If there is no manager left, they should be notified that the "group" will be made inactive and the ownership assigned to the 2-of-clubs administrator.

**Comment by hiimchrislim** [comment]
Perhaps would it be better if the previous owner appointed a new owner rather than the next person in-line?

**Comment by MichaelLiut** [comment]
I like this idea better, yes, let's go with this.
